version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/server

hooks:
  ApplicationStop:
    - location: server_stop.sh
      timeout: 20
      runas: ec2-user
  ApplicationStart:
    - location: server_start.sh
      timeout: 20
      runas: ec2-user
  ValidateService:
    - location: server_validate.sh
      timeout: 60
      runas: ec2-user
