version: 0.2

phases:
  pre_build:
    commands:
      - echo Build started on `date`

  build:
    commands:
      - mvn clean package

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/*.jar
    - appspec.yml
  discard-paths: yes

cache:
  paths:
    - "/root/.m2/**/*"
