version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

  pre_build:
    commands:
      - echo Build started on `date`
      - mvn test

  build:
    commands:
      - mvn clean package

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/spring-boot-todo.jar
    - appspec.yml
  discard-paths: yes
